"""Add longest streak column to User table

Revision ID: 6e335e90f263
Revises: ff2f0e156294
Create Date: 2020-04-26 10:47:05.179238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e335e90f263'
down_revision = 'ff2f0e156294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('longest_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'longest_streak')
    # ### end Alembic commands ###
