"""Add streak column to moods

Revision ID: ff2f0e156294
Revises: de5525efc3a0
Create Date: 2020-04-26 10:16:16.801228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2f0e156294'
down_revision = 'de5525efc3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood', 'streak')
    # ### end Alembic commands ###
